"""
Django settings for myblog project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os # 用于读取环境变量

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 从环境变量读取 SECRET_KEY，如果不存在则使用默认值（兼容本地开发）
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-h00h!9@xze!e2f(asev)2m#y@vh!2=tov#wzjy=i5j487ui+bp'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', '0') == '1'

ALLOWED_HOSTS = os.getenv(
    'ALLOWED_HOSTS',
    'localhost,127.0.0.1'
).split(',')


# Application definition

INSTALLED_APPS = [
    'corsheaders', # corsheader 包，必须在顶部
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    # 自定义app一定要放在最后
    'blog',
    'project',  # 项目展示模块
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # corsheader 中间件，必须在顶部
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ============================================================
# CORS 配置（跨域资源共享）
# ============================================================
# 📌 什么是 CORS？
# 
# CORS (Cross-Origin Resource Sharing) 是浏览器的安全机制。
# 
# 跨域场景：
# - 前端在 https://www.wangshixin.me（Vercel）
# - 后端在 https://api.wangshixin.me（你的服务器）
# - 两者域名不同，浏览器会阻止前端 JS 调用后端 API
# 
# 解决方案：
# 后端需要在响应头添加 Access-Control-Allow-Origin: https://www.wangshixin.me
# 告诉浏览器"允许这个前端域名访问我"
# 
# ============================================================
# 📚 配置逻辑说明
# ============================================================
# 
# 1. 环境变量优先：
#    CORS_ALLOW_ALL_ORIGINS=true → 允许所有域名（⚠️ 仅开发环境！）
# 
# 2. 白名单模式：
#    CORS_ALLOWED_ORIGINS=https://a.com,https://b.com → 只允许指定域名
# 
# 3. 默认本地开发：
#    如果都没设置，使用 localhost:5173（Vite 默认开发端口）
# 
# ============================================================

if os.getenv('CORS_ALLOW_ALL_ORIGINS', 'false').lower() == 'true':
    # 开发模式：允许所有来源（不推荐生产环境！）
    CORS_ALLOW_ALL_ORIGINS = True
else:
    # 生产模式：只允许白名单域名
    origins_env = os.getenv('CORS_ALLOWED_ORIGINS')
    if origins_env:
        # 从环境变量读取，支持逗号分隔多个域名
        CORS_ALLOWED_ORIGINS = [o.strip() for o in origins_env.split(',') if o.strip()]
    else:
        # 默认白名单：本地开发 + 生产前端域名
        CORS_ALLOWED_ORIGINS = [
            # 本地开发（npm run dev）
            "http://localhost:5173",      # Vite 默认端口
            "http://127.0.0.1:5173",
            # 生产环境（Vercel 部署）
            "https://www.wangshixin.me",  # 自定义域名
            # 如果还有 Vercel 默认域名，也可以加上：
            "https://wangshixin-blog.vercel.app",
        ]

# ============================================================
# 💡 常见问题
# ============================================================
# 
# Q1: 为什么前端请求报错 "CORS policy blocked"？
# A1: 检查前端域名是否在上面的白名单中，包括协议（http/https）
# 
# Q2: localhost 和 127.0.0.1 有区别吗？
# A2: 有！浏览器认为它们是不同的域，所以两个都要加
# 
# Q3: 生产环境用 CORS_ALLOW_ALL_ORIGINS=true 可以吗？
# A3: ❌ 不可以！这会让任何网站都能调用你的 API，存在安全风险
# 
# ============================================================

# 终端输出 SQL 日志
LOGGING = {
    'version': 1,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'}
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG'
        }
    }
}

# 禁用 DRF 的 Browsable API
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer', # 只返回Json
        # 'rest_framework.renderers.BrowsableAPIRenderer',  # ← 注释掉这行
    ],
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 数据库配置
# 如果环境变量中存在 POSTGRES_DB，则使用 PostgreSQL
# 否则使用 SQLite（默认）
if os.getenv('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB'),
            'USER': os.getenv('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
            'HOST': os.getenv('POSTGRES_HOST', 'db'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
        }
    }
else:
    # 默认使用 SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# 生产环境静态文件收集目录
# collectstatic 命令会将所有静态文件复制到这里
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 媒体文件配置（用户上传的文件）
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================
# 反向代理 & HTTPS 安全相关配置（解决 CSRF 403 问题）
# -------------------------------------------------------------
# 场景：Nginx 以 HTTP 与后端通信，但对外暴露 HTTPS；如果不告诉 Django
# “真实客户端协议是 https”，Django 会认为请求是 http，从而在 CSRF 中的
# Referer 校验阶段出现不匹配（浏览器提交的 Referer 是 https://...）。
# 结果：登录 / 表单提交可能得到 "CSRF verification failed" (403)。
#
# 关键点：
# 1. SECURE_PROXY_SSL_HEADER 指定使用哪个请求头来判断客户端协议。
#    Nginx 已设置： proxy_set_header X-Forwarded-Proto $scheme;
#    因此这里使用 ('HTTP_X_FORWARDED_PROTO', 'https')。
# 2. USE_X_FORWARDED_HOST 允许 Django 使用 X-Forwarded-Host 作为请求主机，
#    防止内部容器名影响构建绝对 URL。
# 3. CSRF_TRUSTED_ORIGINS 需要包含 HTTPS 域名；否则 Referer 校验可能失败。
# 4. CSRF_COOKIE_SECURE / SESSION_COOKIE_SECURE 在 HTTPS 下务必开启，避免明文传输。
# 5. 可根据需要开启 SECURE_HSTS_SECONDS 等强化（已在 Nginx 添加 HSTS）。
# =============================================================

# 告诉 Django 在反向代理后使用 X-Forwarded-Proto 判断是否为 HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 使用反向代理的 Host（避免生成内部主机名）
USE_X_FORWARDED_HOST = True

# 信任的 HTTPS 来源（必须包含协议前缀），用于 CSRF Referer 校验
CSRF_TRUSTED_ORIGINS = [
    'https://api.wangshixin.me',
    'https://www.wangshixin.me',
]

# 在 HTTPS 下只通过安全通道发送 Cookie
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# 可选：如果需要跨站点前端访问 API 的 Cookie（此项目暂不需要）
# CSRF_COOKIE_SAMESITE = 'None'
# SESSION_COOKIE_SAMESITE = 'None'

# 可选的额外安全强化（按需启用）：
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
# SECURE_HSTS_SECONDS = 63072000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
