# Generated by Django 5.2.8 on 2026-01-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='技术名称')),
                ('icon_url', models.URLField(blank=True, verbose_name='图标URL')),
                ('official_url', models.URLField(blank=True, verbose_name='官网链接')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='标签颜色')),
            ],
            options={
                'verbose_name': '技术栈',
                'verbose_name_plural': '技术栈',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='项目名称')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='URL标识')),
                ('description', models.TextField(verbose_name='项目简介')),
                ('content', models.TextField(blank=True, verbose_name='详细介绍')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/covers/', verbose_name='封面图片')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub链接')),
                ('demo_url', models.URLField(blank=True, verbose_name='演示地址')),
                ('status', models.CharField(choices=[('developing', '开发中'), ('completed', '已完成'), ('online', '已上线'), ('offline', '暂时下线')], default='developing', max_length=20, verbose_name='项目状态')),
                ('is_featured', models.BooleanField(default=False, verbose_name='精选项目')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tech_stack', models.ManyToManyField(blank=True, related_name='projects', to='project.techstack', verbose_name='技术栈')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-is_featured', '-sort_order', '-created_at'],
            },
        ),
    ]
